---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible molecule yamllint ansible-lint molecule-docker
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
  - pip install docker
script:
  - molecule lint
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
